### ISSUE TITLE
Error opening UDDL_SDM_Min.uddl

### ISSUE THREAD

**Issue by Thomcray** [Epistimis/UDDL#38]
I started the task all over again a couple of times because I wasn't able to format the UDDL_SDM_Min.uddl file.

This time I'm getting an unresolved compilation error. Screenshot attached.
![Screenshot (90)](https://user-images.githubusercontent.com/68615268/220980190-37dc2761-e044-4f79-be5c-001ee1bfac9a.png)

**Comment by steve-hickman-epistimis** [comment]
Create a new discussion here:
https://github.com/Epistimis/UDDL/discussions

Attach screen shots from both the first and second Eclipse, attach console logs from both, and copies of the Error pane contents from both the first and second Eclipse. I’ll address it there.

Regards –

Steve Hickman

From: Thompson Terna ***@***.***>
Date: Thursday, February 23, 2023 at 9:12 AM
To: Epistimis/UDDL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Epistimis/UDDL] Error opening UDDL_SDM_Min.uddl (Issue #38)

I started the task all over again a couple of times because I wasn't able to format the UDDL_SDM_Min.uddl file.

This time I'm getting an unresolved compilation error. Screenshot attached.
[Screenshot (90)]<https://user-images.githubusercontent.com/68615268/220980190-37dc2761-e044-4f79-be5c-001ee1bfac9a.png>

**Comment by steve-hickman-epistimis** [comment]
Or just reopen this issue and add it there.

Regards –

Steve Hickman

From: Steve Hickman ***@***.***>
Date: Thursday, February 23, 2023 at 9:17 AM
To: Epistimis/UDDL ***@***.***>
Subject: Re: [Epistimis/UDDL] Error opening UDDL_SDM_Min.uddl (Issue #38)
Create a new discussion here:
https://github.com/Epistimis/UDDL/discussions

Attach screen shots from both the first and second Eclipse, attach console logs from both, and copies of the Error pane contents from both the first and second Eclipse. I’ll address it there.

Regards –

Steve Hickman

From: Thompson Terna ***@***.***>
Date: Thursday, February 23, 2023 at 9:12 AM
To: Epistimis/UDDL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Epistimis/UDDL] Error opening UDDL_SDM_Min.uddl (Issue #38)

I started the task all over again a couple of times because I wasn't able to format the UDDL_SDM_Min.uddl file.

This time I'm getting an unresolved compilation error. Screenshot attached.
[Screenshot (90)]<https://user-images.githubusercontent.com/68615268/220980190-37dc2761-e044-4f79-be5c-001ee1bfac9a.png>

**Comment by steve-hickman-epistimis** [comment]
Being addressed in https://github.com/Epistimis/UDDL/discussions/40
